### ISSUE TITLE
How to `report_hyperparameter_tuning_metric` inside `tf.estimator.train_and_evaluate`?

### ISSUE THREAD

**Issue by schmidt-jake** [GoogleCloudPlatform/cloudml-hypertune#1]
I'm running hyperparameter tuning with a custom container. I've followed the [tutorial](https://cloud.google.com/ml-engine/docs/custom-containers-training#submit_a_hyperparameter_tuning_job) but I'd like some guidance on how I might be able to report metrics to the hypertune service during the `train_and_estimate` call instead of afterwards.

**Comment by thebinaryone1** [comment]
Do you mean this : https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate ?

Well you can add some hooks to train_spec and eval_spec.

**Comment by thebinaryone1** [comment]
You can write an end method such as the following :

```
class HypertuneHook(tf.train.SessionRunHook):
  def end(self, session):
      # Get the global step
      step_variable = session.graph.get_collection('global_step')
      global_step = session.run(step_variable)[0]

      to_report_value = None

      # Get all the metric values
      metric_variables = session.graph.get_collection('metric_variables')
      self.variable_names = [variable.name for variable in metric_variables]
      self.metric_values = session.run(metric_variables)
```
